[package]
name = "assembler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
computils = { path = "../computils", version = "*", features = ["assembler", "error", "instr"] }
